# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'LocalTalk' do

  pod 'PonyDebugger', :git => 'https://github.com/square/PonyDebugger.git'
  pod 'JSQMessagesViewController'

end

target 'LocalTalkTests' do

end

